
server:
  port: 8082

#management:
#  port: 8083
#  context-path: /admin

security:
 basic:
  enabled: false
 oauth2:
   client:
     client-id: demo-resource
     client-secret: demosecret
   resource:
    jwt:
     key-uri: http://localhost:8080/uaa/token_key  
#     token-info-uri: http://localhost:8080/uaa/check_token

logging:
 level:
  org.springframework.security: DEBUG